# Generated by Django 5.2.6 on 2025-10-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True)),
                ('phone_country_code', models.CharField(choices=[('+1', '🇺🇸 United States'), ('+44', '🇬🇧 United Kingdom'), ('+91', '🇮🇳 India'), ('+86', '🇨🇳 China'), ('+49', '🇩🇪 Germany'), ('+33', '🇫🇷 France'), ('+81', '🇯🇵 Japan'), ('+61', '🇦🇺 Australia'), ('+55', '🇧🇷 Brazil'), ('+39', '🇮🇹 Italy'), ('+34', '🇪🇸 Spain'), ('+7', '🇷🇺 Russia'), ('+82', '🇰🇷 South Korea'), ('+31', '🇳🇱 Netherlands'), ('+46', '🇸🇪 Sweden'), ('+47', '🇳🇴 Norway'), ('+45', '🇩🇰 Denmark'), ('+41', '🇨🇭 Switzerland'), ('+43', '🇦🇹 Austria'), ('+32', '🇧🇪 Belgium')], default='+1', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
