# Generated by Django 5.2.7 on 2025-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pregnancy', models.BooleanField(default=False)),
                ('orthodontics', models.BooleanField(default=False)),
                ('teething_to_24_months', models.BooleanField(default=False)),
                ('age_2_to_5', models.BooleanField(default=False)),
                ('age_6_to_12', models.BooleanField(default=False)),
                ('age_13_and_above', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
